# Generated by Django 2.2.4 on 2019-08-21 11:48

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('about_myself', models.TextField(blank=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('avatar', models.ImageField(upload_to='images/')),
                ('age', models.IntegerField(default=25)),
                ('age_for_search', multiselectfield.db.fields.MultiSelectField(choices=[(1, '15-20'), (2, '20-25'), (3, '25-30'), (4, '30-35'), (5, '35-40'), (6, '40-45'), (7, '45-50'), (8, '50-60'), (9, 'more than 60')], default='20-25', max_length=17, verbose_name='Preferred age for partner')),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0, verbose_name='Gender')),
                ('gender_for_search', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Male'), (1, 'Female')], default=0, max_length=3, verbose_name="I'm searching for")),
                ('interests', models.CharField(blank=True, max_length=50)),
                ('create_date', models.DateTimeField(null=True, verbose_name='date created')),
                ('email', models.EmailField(max_length=254)),
                ('movie_preferences', multiselectfield.db.fields.MultiSelectField(choices=[('No preferences', 'No preferences'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Action / thriller', 'Action / thriller'), ('Animated film', 'Animated film'), ('Horror', 'Horror'), ('Documentary', 'Documentary'), ('Science fiction', 'Science fiction'), ('Romance comedy', 'Romance comedy'), ('Other', 'Other')], default='No preferences', max_length=125)),
                ('literature_preferences', multiselectfield.db.fields.MultiSelectField(choices=[('No preferences', 'No preferences'), ('Picture book', 'Picture book'), ('Humor', 'Humor'), ('Historical fiction', 'Historical fiction'), ('Mystery', 'Mystery'), ('Folklore', 'Folklore'), ('Fan fiction', 'Fan fiction'), ('Fairy tale', 'Fairy tale'), ('Classic', 'Classic'), ('Horror', 'Horror'), ('Romance novel', 'Romance novel'), ('Western', 'Western'), ('Fantasy', 'Fantasy'), ('Detective fiction', 'Detective fiction'), ('Science fiction', 'Science fiction'), ('Crime', 'Crime'), ('Other', 'Other')], default='No preferences', max_length=183)),
                ('music_preferences', multiselectfield.db.fields.MultiSelectField(choices=[('no preferences', 'no preferences'), ('blues', 'blues'), ('classical', 'classical'), ('country', 'country'), ('dance', 'dance'), ('easy listening', 'easy listening'), ('electronic', 'electronic'), ('folk\t', 'folk'), ('heavy metal', 'heavy metal'), ('hip hop', 'hip hop'), ('jazz\t', 'jazz'), ('latin', 'latin'), ('opera', 'opera'), ('pop', 'pop'), ('rap', 'rap'), ('reggae', 'reggae'), ('rock', 'rock'), ('techno', 'techno'), ('other', 'other')], default='no preferences', max_length=147)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
